# Generated by Django 2.1.7 on 2019-08-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190826_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(default='nothing', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('g', 'g'), ('cup', 'cup'), ('Tbs', 'Tbs'), ('tsp', 'tsp'), (' ', ' ')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='SavedRecipe',
        ),
    ]
